# Generated by Django 4.2 on 2024-04-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, null=True)),
                ('referrer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral_set', to=settings.AUTH_USER_MODEL)),
                ('refree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refree_referral_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
