# Generated by Django 4.2 on 2024-04-08 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral_system',
            name='refree',
        ),
        migrations.AlterField(
            model_name='referral_system',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_referral_set', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='Referee_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, null=True)),
                ('refree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refree_referral_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
